baseURL = "https://trontria.com"
languageCode = "en-us"
title = "tròn trịa"
theme = "purehugo"
Paginate = 10

[params]
  # twitterName = "nquangtrung90"
  githubName = "nquangtrung"
  # stackOverflowId = "#######"
  linkedinName = "trung-nguyễn-109b523a"
  facebookName = "supertrontria"
  description = "tech, art and life"
  google_analytics = "UA-xxxxxx-xx"
  hideSidebarIconText = true
